# Generated by Django 5.1 on 2024-12-03 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_category', models.CharField(choices=[('Drink', 'Drink'), ('Chips', 'Chips'), ('Candy', 'Candy'), ('Cookies', 'Cookies')], default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
            ],
        ),
    ]
