# Generated by Django 5.0.6 on 2025-07-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipient_code',
            field=models.CharField(default=12345678, help_text="Please input the receipient/student's unique wallet code", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='receipient_email',
            field=models.EmailField(default=12345678, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(help_text='Input your email', max_length=254),
        ),
    ]
