# Generated by Django 5.1 on 2024-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_receipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_email',
            field=models.EmailField(default=0, help_text="Please input the receipent/student's email", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(help_text='Please input your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipient_code',
            field=models.CharField(help_text="Please input the receipent/student's unique wallet code", max_length=20),
        ),
    ]
