# Generated by Django 5.1 on 2024-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_student_email_alter_payment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student_email',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipient_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(help_text='Input your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipient_code',
            field=models.CharField(help_text="Please input the receipient/student's unique wallet code", max_length=20),
        ),
    ]
