# Generated by Django 5.1 on 2024-09-29 21:40

import authentication.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_financeadmin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grad_year', models.PositiveSmallIntegerField(blank=True, default=2025, null=True)),
                ('year_group', models.CharField(choices=[('MYP4', 'MYP4'), ('MYP5', 'MYP5'), ('DP1', 'DP1'), ('DP2', 'DP2')], default='', max_length=255)),
                ('hostel_group', models.CharField(choices=[('Titan', 'Titan'), ('Trojan', 'Trojan'), ('Viking', 'Viking'), ('Spartan', 'Spartan')], default='Titan', max_length=255)),
                ('hostel', models.CharField(choices=[('Tana', 'Tana'), ('Kariba', 'Kariba'), ('Juba', 'Juba'), ('Congo', 'Congo'), ('Niger', 'Niger'), ('Densu', 'Densu'), ('Turkana', 'Turkana'), ('Cavally', 'Cavally'), ('Ankobra', 'Ankobra'), ('Volta', 'Volta'), ('Nile', 'Nile'), ('Limpopo', 'Limpopo'), ('Mano', 'Mano'), ('Sassandra', 'Sassandra'), ('Zambezi', 'Zambezi'), ('Kagera', 'Kagera'), ('Tanganyika', 'Tanganyika')], default='Tana', max_length=255)),
                ('room_num', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('parent1_email', models.EmailField(blank=True, default='', max_length=254)),
                ('parent1_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent1_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent2_email', models.EmailField(blank=True, default='', max_length=254)),
                ('parent2_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent2_last_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='finance_team',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finance_team', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'finance_team',
                'verbose_name_plural': 'finance_teams',
            },
        ),
        migrations.CreateModel(
            name='shop_owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vendor_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
