# Generated by Django 5.0.6 on 2025-07-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuckshop',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tuckshop_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Tuckshop',
                'verbose_name_plural': 'Tuckshop',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='student_code',
            field=models.CharField(blank=True, default='', max_length=7, unique='True'),
        ),
    ]
