# Generated by Django 5.1 on 2024-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hostel',
            field=models.CharField(choices=[('Tana', 'Tana'), ('Kariba', 'Kariba'), ('Juba', 'Juba'), ('Congo', 'Congo'), ('Niger', 'Niger'), ('Densu', 'Densu'), ('Turkana', 'Turkana'), ('Cavally', 'Cavally'), ('Ankobra', 'Ankobra'), ('Volta', 'Volta'), ('Nile', 'Nile'), ('Limpopo', 'Limpopo'), ('Mano', 'Mano'), ('Sassandra', 'Sassandra'), ('Zambezi', 'Zambezi'), ('Kagera', 'Kagera'), ('Tanganyika', 'Tanganyika')], default='Tana', max_length=255),
        ),
    ]
