# Generated by Django 5.1 on 2025-01-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tuckshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='student_code',
            field=models.CharField(blank=True, default='', max_length=7, unique='True'),
        ),
    ]
