# Generated by Django 5.1 on 2024-09-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_owner',
            name='user',
        ),
        migrations.DeleteModel(
            name='finance_team',
        ),
        migrations.DeleteModel(
            name='shop_owner',
        ),
    ]
