# Generated by Django 5.1 on 2024-09-16 10:06

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_shop_owner_user_delete_finance_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance_team',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='finance_team', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'finance_team',
                'verbose_name_plural': 'finance_teams',
            },
            bases=('authentication.user',),
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='shop_owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='shop_owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vendor_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
            bases=('authentication.user',),
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
