# Generated by Django 5.1 on 2024-09-17 19:17

import authentication.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_finance_team_shop_owner_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent1_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent2_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent2_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent1_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grad_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hostel_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent1_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent2_last_name',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='finance_team',
            name='name',
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grad_year', models.PositiveSmallIntegerField(blank=True, default=2025, null=True)),
                ('year_group', models.CharField(choices=[('MYP4', 'MYP4'), ('MYP5', 'MYP5'), ('DP1', 'DP1'), ('DP2', 'DP2')], default='', max_length=255)),
                ('hostel_group', models.CharField(choices=[('Titan', 'Titan'), ('Trojan', 'Trojan'), ('Viking', 'Viking'), ('Spartan', 'Spartan')], default='Titan', max_length=255)),
                ('hostel', models.CharField(choices=[('Tana', 'Tana'), ('Kariba', 'Kariba'), ('Juba', 'Juba'), ('Congo', 'Congo'), ('Niger', 'Niger'), ('Densu', 'Densu'), ('Turkana', 'Turkana'), ('Cavally', 'Cavally'), ('Ankobra', 'Ankobra'), ('Volta', 'Volta'), ('Nile', 'Nile'), ('Limpopo', 'Limpopo'), ('Mano', 'Mano'), ('Sassandra', 'Sassandra'), ('Zambezi', 'Zambezi'), ('Kagera', 'Kagera'), ('Tanganyika', 'Tanganyika')], default='Tana', max_length=255)),
                ('room_num', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('parent1_email', models.EmailField(blank=True, default='', max_length=254)),
                ('parent1_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent1_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent2_email', models.EmailField(blank=True, default='', max_length=254)),
                ('parent2_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('parent2_last_name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.user',),
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
