# Generated by Django 5.0.6 on 2025-07-19 00:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuckshop', '0002_order_alter_product_options_alter_product_price_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='password',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_shopowner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_code',
            field=models.CharField(default=123456, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transaction_from', models.CharField(default='', max_length=100)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuckshop.order')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallet')),
            ],
        ),
    ]
