# Generated by Django 4.2.14 on 2024-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallet_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
