# Generated by Django 4.2.14 on 2024-08-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_wallet_password_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
