# Generated by Django 4.2.14 on 2024-08-08 21:39

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=6)),
        ),
    ]
