# Generated by Django 4.2.14 on 2024-08-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_wallet_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='password',
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
