# Generated by Django 5.1 on 2024-09-12 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_wallet_password_wallet_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='private_code',
            field=models.CharField(default=0, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
