# Generated by Django 5.1 on 2024-09-12 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_transaction_id_transaction_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
