# Generated by Django 5.1 on 2024-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_created_alter_wallet_private_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_shopowner',
            field=models.BooleanField(default=False),
        ),
    ]
