# Generated by Django 5.1 on 2024-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_wallet_is_shopowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=12),
        ),
    ]
