# Generated by Django 5.1 on 2024-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_wallet_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
