# Generated by Django 5.1 on 2025-01-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuckshop', '0003_alter_product_options_alter_product_price'),
        ('wallet', '0013_transaction_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuckshop.order'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='private_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
