# Generated by Django 5.1 on 2025-01-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_transaction_order_alter_wallet_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
