# Generated by Django 5.1 on 2025-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_transaction_transaction_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(default='', max_length=100),
        ),
    ]
